# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab03pantalla():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab03pantalla(self):
    self.driver.get("http://127.0.0.1:8080/")
    self.driver.set_window_size(1559, 796)
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    self.driver.find_element(By.ID, "add-movie").click()
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("Volver al futuro")
    self.driver.find_element(By.NAME, "year").click()
    self.driver.find_element(By.NAME, "year").send_keys("1985")
    self.driver.find_element(By.NAME, "director").click()
    self.driver.find_element(By.NAME, "director").send_keys("Robert Zemeckis")
    self.driver.find_element(By.NAME, "rating").click()
    self.driver.find_element(By.NAME, "rating").send_keys("4")
    self.driver.find_element(By.NAME, "review").click()
    self.driver.find_element(By.NAME, "review").send_keys("«obra maestra del cine de adolescentes. Divertida, original y muy entretenida»")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "add-movie").click()
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("Los Simpsons")
    self.driver.find_element(By.NAME, "year").click()
    self.driver.find_element(By.NAME, "year").send_keys("2007")
    self.driver.find_element(By.NAME, "director").click()
    self.driver.find_element(By.NAME, "director").send_keys("David Silverman")
    self.driver.find_element(By.NAME, "rating").click()
    self.driver.find_element(By.NAME, "rating").send_keys("4")
    self.driver.find_element(By.NAME, "review").click()
    self.driver.find_element(By.NAME, "review").send_keys("Entretenida")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Dune").click()
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    self.driver.find_element(By.NAME, "review").send_keys("Gran adaptación de una novela clásica de ciencia ficción.")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Elvis").click()
    self.driver.find_element(By.NAME, "review").click()
    self.driver.find_element(By.NAME, "review").send_keys("Hype película biográfica estilizada del Rey.")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
