from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

chrome_options = Options()
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

driver = webdriver.Chrome(options=chrome_options)
driver.get("http://localhost:8080/")
driver.set_window_size(1928, 1048)
driver.find_element(By.ID, "add-movie").click()
driver.find_element(By.NAME, "title").click()
driver.find_element(By.NAME, "title").send_keys("Alone in te Dark")
import time
print('esperaremos 3 segundos' )
time.sleep(3)
driver.find_element(By.NAME, "year").click()
driver.find_element(By.NAME, "year").send_keys("2022")
print('esperaremos 5 segundos' )
time.sleep(5)
driver.find_element(By.NAME, "director").click()
driver.find_element(By.NAME, "director").send_keys("Brant Daugherty")
print('esperaremos 1 segundos' )
time.sleep(1)
driver.find_element(By.NAME, "rating").click()
driver.find_element(By.NAME, "rating").send_keys("5")
print('esperaremos 2 segundos' )
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, ".btn").click()
print('esperaremos 2 segundos' )
time.sleep(2)
driver.find_element(By.ID, "add-movie").click()
print('esperaremos 3 segundos' )
time.sleep(3)

driver.find_element(By.NAME, "title").click()
driver.find_element(By.NAME, "title").send_keys("Alone in te Dark")
print('esperaremos 2 segundos' )
time.sleep(2)
driver.find_element(By.NAME, "year").click()
driver.find_element(By.NAME, "year").send_keys("2005")
print('esperaremos 2 segundos' )
time.sleep(2)
driver.find_element(By.NAME, "director").click()
driver.find_element(By.NAME, "director").send_keys("Uwe Boll")
print('esperaremos 2 segundos' )
time.sleep(2)
driver.find_element(By.NAME, "rating").click()
driver.find_element(By.NAME, "rating").send_keys("2")
print('esperaremos 2 segundos' )
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, ".btn").click()
print('esperaremos 2 segundos' )
time.sleep(2)
input1 = "Great adaption of a cassic sci-fi novel"
driver.get("https://translate.google.com/?sl=en&tl=es&text="+input1+"&op=translate")
time.sleep(5)
input2 = "Hype stylized biopic of the King"
driver.get("https://translate.google.com/?sl=en&tl=es&text="+input2+"&op=translate")
time.sleep(5)
